export default {
  splash_screen: require('../assets/Splash.png'),
  community_safety: require('../assets/communitySafety.png'),
  realTime_incitent: require('../assets/realtime.png'),
  crimePrevention: require('../assets/crimePrevention.png'),
  rightArrow: require('../assets/rightArrow.png'),
  anonymously: require('../assets/anonymously.png'),
  sheildRed: require('../assets/Shieldred.png'),
  ic_gmail: require('../assets/gmail.png'),
  ic_thumb: require('../assets/thumb.png'),
  plusHexa: require('../assets/plusHexa.png'),
  home: require('../assets/home.png'),
  dashboard: require('../assets/dashboard.png'),
  community: require('../assets/community.png'),
  profile: require('../assets/profile.png'),
  mapDummy: require('../assets/mapDummy.png'),
  codesamples: require('../assets/codesamples.png'),
  campaign: require('../assets/campaign.png'),
  notification_bell: require('../assets/notification_bell.png'),

  leftArrow: require('../assets/arrowLeft.png'),
  clock: require('../assets/clock.png'),
  nearBy: require('../assets/nearBy.png'),
  locationblue: require('../assets/locationblue.png'),
  samplePeopleImage: require('../assets/samplePeopleImage.png'),
  hamburger: require('../assets/hamburger.png'),
  codesamplesPremium: require('../assets/codesamplesPremium.png'),
  calender: require('../assets/calender.png'),
  progressChart: require('../assets/progressChart.png'),
  halfAlert: require('../assets/halfAlert.png'),
  handsing: require('../assets/handsing.png'),
  rightIndicator: require('../assets/rightIndicator.png'),
  high_severity: require('../assets/high_severity.png'),
  medium_severity: require('../assets/medium_severity.png'),
  low_severity: require('../assets/low_severity.png'),

  crime_high_severity: require('../assets/crimeHighSeverity.png'),
  crime_medium_severity: require('../assets/crimeMediumSeverity.png'),
  crime_low_severity: require('../assets/crimeLowSeverity.png'),

  incident_high_severity: require('../assets/incidentHighSeverity.png'),
  incident_medium_severity: require('../assets/incidentMediumSeverity.png'),
  incident_low_severity: require('../assets/incidentLowSeverity.png'),
  verified_green: require('../assets/verified.png'),
  speaker_red: require('../assets/speaker.png'),
  handRed: require('../assets/handRed.png'),
  sheild: require('../assets/sheild.png'),
  x_hexa: require('../assets/x_hexa.png'),
  pin: require('../assets/pin.png'),
  gps: require('../assets/gps.png'),
  push_pin: require('../assets/push_pin.png'),
  attachment: require('../assets/attachment.png'),
  splash_video: require('../assets/codesamplesIntro.mp4'),
};
