export const strings = {
  // intro screens
  community_safety: 'Community Safety',
  community_safety_des:
    'Your go-to platform for community safety. Here, you can anonymously report and stay informed about incidents in your area. Your safety is our priority, and your identity remains confidential throughout the process.',
  real_time_incident: 'Real-time incident map',
  real_time_incident_des:
    'Explore key features like our real-time incident map, allowing you to visualize crime in your vicinity. Customize your experience with incident filtering, and contribute to a safer community by reporting anonymously.',
  crime_prevention: 'Crime Prevention',
  crime_prevention_des:
    'Explore key features like our real-time incident map, allowing you to visualize crime in your vicinity. Customize your experience with incident filtering, and contribute to a safer community by reporting anonymously.',

  // Authentication stack
  your_privacy_matter: 'Your Privacy Matters',
  your_privacy_matter_des: `The data gathered during the signup process is solely for record-keeping purposes. When reporting incidents, your contributions will be presented as 'Anonymous' to prioritize the privacy and security of our community members.`,
  have_an_account: 'Have an Account?',
  new_here: 'New here?',
  sign_in: 'Sign In',
  sign_up: 'Sign Up',
  password: 'Password',
  user_name: 'UserName',
  safer_community: 'for a Safer Community',
  login_details: 'Enter your login details',
  invalid_email_format: 'Invalid email format',
  password_validation_text: 'Password length: Minimum 8 characters',
  one_lowercase_case: 'One lowercase letter',
  one_uppercase_case: 'One uppercase letter',
  one_special_case: 'One special character',
  one_number: 'One number',
  terms_conditions_error_text: 'Please Accept Terms and Conditions',
  terms_condition_text:
    'By checking this box, you agree to the terms \noutlined in our',
  sign_in_anonymously: 'Sign In Anonymously',
  random_user_name: 'Username is randomly generated',

  forrgotten_password: 'Forgot Password?',
  forrgotten_password_des: 'Enter the email associated with your account',
  email_address: 'Email Address',

  new_here: 'New here?',
  sendOtp: 'Send OTP',
  otp_sent: 'OTP Sent',
  otp_sent_des:
    'Check your email for the OTP to reset your password. Enter it below to proceed.',
  submit: 'Submit',
  reset_pass: 'Reset Password',
  reset_pass_des: 'New password must be different',
  password_error: 'Please enter valid password.',
  success_reset: 'Password reset successful.',
  success: 'Success!',
  incorrectInfo: 'Incorrect password. Please try again.',

  event_details: 'Event Details',
  more: 'more',
  openinMap: 'Open in Map',
  addAComment: 'Add Comment',
  locationAccess: 'Location Access Required',
  locationAccessText:
    'To use this feature, please enable location services in your device settings.',
  cancel: 'Cancel',
  goSettings: 'Go to Settings',
  alert: 'Alert',
  total_alert: 'Total Alert/Threat',
  load_more: 'Load More',
  show_less: 'Show Less',
  crime: 'Crime',
  incident: 'Incident',
  event: 'Event',
  event_type: 'Event Type',
  severity_level: 'Severity Level',
  high_severity_level: 'High Severity Level',
  radius: 'Radius',
  reset: 'Reset',
  apply: 'Apply',
  cancel: 'Cancel',
  comments_details: 'Comment Details',

  select_event: 'Select event',
  report_crime: 'Report Crime',
  report_incident: 'Report Incident',
  reset: 'Reset',
  statisticsFilter: 'Statistics Filter',
  filterbyDuration: 'Filter by duration',
  filterbyDate: 'Filter by date range',
  // ------ //
  reportCrimeHeader: {
    crime_type: 'Select the type of crime',
    date_picker_header: 'When did the crime occur?',
    time_picker_header: 'If you know the time, please fill it in',
    severity_level_header: 'Rate the severity of the crime',
    crime_add_header: 'Address of Crime Scene',
    description_header: 'Describe crime & crime scene in detail',
  },

  whoops: 'Whoops!',
  sign_in_with_email: 'Sign In with Email',

  confirm_pass: 'Please enter same password',
  try_again: 'Try again',
};
