// export const EventDetailsData = {
//   id: 1,
//   title: 'Armed Robbery In Progress',
//   map_view:
//     'https://drive.google.com/file/d/15CnSHEkzdMdC-S65DFhrhqi31-o5vFWH/view?pli=1',
//   address: 'Shivalik Shilp',
//   city: 'Ahmedabad',
//   state: 'Gujarat',
//   suite: null,
//   zip_code: '34534',
//   country: 'India',
//   latitude: '23.0270241',
//   longitude: '72.5037668',
//   date: '2023-11-17',
//   day: '',
//   time: '12:45:00',
//   crime_type_id: 18,
//   severity_level_id: 2,
//   created_by: 2,
//   community_id: null,
//   details:
//     'A gang with a White Toyota is reported to be carrying A gang with a White Toyota is reported to be carrying A gang with a White Toyota is reported to be carrying A gang with a White Toyota is reported to be carrying A gang with a White Toyota is reported to be carrying A gang with a White Toyota is reported to be carrying A gang with a White Toyota is reported to be carrying firearms in the X area. It is advisable to stay in your premises for the time being as it may pose a \r\ndanger',
//   explicit_content: 1,
//   is_verified: 0,
//   status: 1,
//   alert_created: 0,
//   created_at: '2023-11-17T19:50:26.000000Z',
//   updated_at: null,
//   distance: 0.8503938981231828,
//   severity_level: {
//     id: 2,
//     name: 'Moderate',
//     range: '4 to 6',
//     color_code: 'Orange',
//     status: 1,
//     created_at: '2023-11-17T11:47:17.000000Z',
//     updated_at: '2023-11-17T11:47:17.000000Z',
//   },
//   incident_alert: {
//     id: 1,
//     details: 'sdasd',
//     created_by: 3,
//     incident_id: 1,
//     status: 1,
//     alert_type: 'alert',
//     created_at: '2023-12-04T18:37:40.000000Z',
//     updated_at: null,
//   },
//   media: [
//     {
//       id: 1,
//       name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
//       uploaded_name: '',
//       type: 'video/mp4',
//       incident_id: 1,
//       created_at: null,
//       updated_at: null,
//     },
//     {
//       id: 2,
//       name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
//       uploaded_name: '',
//       type: 'video/mp4',
//       incident_id: 1,
//       created_at: null,
//       updated_at: null,
//     },
//     {
//       id: 3,
//       name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
//       uploaded_name: 'Cats.jpg',
//       type: 'image/jpeg',
//       incident_id: 1,
//       created_at: '2023-11-28T13:42:03.000000Z',
//       updated_at: '2023-11-28T13:42:03.000000Z',
//     },
//     {
//       id: 4,
//       name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
//       uploaded_name: 'Eyes.jpg',
//       type: 'image/jpeg',
//       incident_id: 1,
//       created_at: '2023-11-28T13:42:03.000000Z',
//       updated_at: '2023-11-28T13:42:03.000000Z',
//     },
//     {
//       id: 5,
//       name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
//       uploaded_name: 'Orange.jpg',
//       type: 'image/jpeg',
//       incident_id: 1,
//       created_at: '2023-11-28T13:42:03.000000Z',
//       updated_at: '2023-11-28T13:42:03.000000Z',
//     },
//   ],
// };

export const EventDetailsData = {
  id: 4,
  title: 'Armed Robbery In Progress',
  map_view:
    'https://www.google.co.in/maps/place/Parimal+Garden/@23.0208367,72.5086508,14z/data=!4m6!3m5!1s0x395e84fb558f676b:0x7c6636f0c8a9648e!8m2!3d23.0203135!4d72.5561606!16s%2Fg%2F1tkc526m?entry=ttu',
  address: 'Gita Mandir',
  city: 'Ahmedabad',
  state: 'Gujarat',
  suite: 'CG Road',
  zip_code: '380026',
  country: 'India',
  latitude: '23.0020033',
  longitude: '72.5597094',
  date: '2023-11-28',
  day: '',
  time: '12:45:00',
  crime_type_id: 17,
  severity_level_id: 2,
  created_by: 4,
  community_id: null,
  details: 'It is a crime',
  explicit_content: 0,
  is_verified: 0,
  status: 1,
  alert_created: 0,
  created_at: '2023-11-28T14:02:38.000000Z',
  updated_at: '2023-11-28T14:02:38.000000Z',
  total_comments_count: 8,
  incident_alert_count: 1,
  distance: 8.187942707298596,
  comments: {
    current_page: 1,
    data: [
      {
        id: 1,
        text: 'Main one',
        user_id: 4,
        incident_id: 4,
        comment_id: null,
        parent_id: null,
        created_at: '2023-12-06T06:34:22.000000Z',
        updated_at: '2023-12-06T06:34:22.000000Z',
        commented_by: {
          id: 4,
          role_id: 1,
          type_id: 5,
          created_by: null,
          name: 'Kassandra Hermiston',
          username: null,
          email: 'komalshukla@mailinator.com',
          email_verified_at: null,
          credibility_level: null,
          status: 0,
          avatar:
            'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
          created_at: '2023-11-27T08:01:30.000000Z',
          updated_at: '2023-12-12T14:35:16.000000Z',
        },
      },
      {
        id: 7,
        text: 'Main',
        user_id: 4,
        incident_id: 4,
        comment_id: null,
        parent_id: null,
        created_at: '2023-12-06T06:46:23.000000Z',
        updated_at: '2023-12-06T06:46:23.000000Z',
        commented_by: {
          id: 4,
          role_id: 1,
          type_id: 5,
          created_by: null,
          name: 'Kassandra Hermiston',
          username: null,
          email: 'komalshukla@mailinator.com',
          email_verified_at: null,
          credibility_level: null,
          status: 0,
          avatar:
            'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
          created_at: '2023-11-27T08:01:30.000000Z',
          updated_at: '2023-12-12T14:35:16.000000Z',
        },
      },
    ],
    first_page_url: 'http://codesamples.local/api/incident-detailed/4?page=1',
    from: 1,
    last_page: 1,
    last_page_url: 'http://codesamples.local/api/incident-detailed/4?page=1',
    links: [
      {
        url: null,
        label: '&laquo; Previous',
        active: false,
      },
      {
        url: 'http://codesamples.local/api/incident-detailed/4?page=1',
        label: '1',
        active: true,
      },
      {
        url: null,
        label: 'Next &raquo;',
        active: false,
      },
    ],
    next_page_url: null,
    path: 'http://codesamples.local/api/incident-detailed/4',
    per_page: 10,
    prev_page_url: null,
    to: 2,
    total: 2,
  },
  crime_type: {
    id: 17,
    severity_level_id: 2,
    name: 'Komal Shukla',
    type: 'crime',
    status: 1,
    created_at: '2023-12-08T08:21:14.000000Z',
    updated_at: '2023-12-08T09:33:36.000000Z',
  },
  media: [
    {
      id: 6,
      name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
      uploaded_name: 'Cats.jpg',
      type: 'image/jpeg',
      incident_id: 4,
      created_at: '2023-11-28T14:02:38.000000Z',
      updated_at: '2023-11-28T14:02:38.000000Z',
    },
    {
      id: 7,
      name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
      uploaded_name: 'Eyes.jpg',
      type: 'image/jpeg',
      incident_id: 4,
      created_at: '2023-11-28T14:02:38.000000Z',
      updated_at: '2023-11-28T14:02:38.000000Z',
    },
    {
      id: 8,
      name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
      uploaded_name: 'Orange.jpg',
      type: 'image/jpeg',
      incident_id: 4,
      created_at: '2023-11-28T14:02:38.000000Z',
      updated_at: '2023-11-28T14:02:38.000000Z',
    },
  ],
  severity_level: {
    id: 2,
    name: 'Moderate',
    range: '4 to 6',
    color_code: 'Orange',
    status: 1,
    created_at: '2023-11-17T11:47:17.000000Z',
    updated_at: '2023-11-17T11:47:17.000000Z',
  },
  incident_alert: [
    {
      id: 1,
      details:
        'URGENT: Armed robbery reported at 123 Main Street. Please avoid the area. Stay indoors and remain vigilant. Police are on the scene. Updates to follow.',
      created_by: {
        id: 3,
        role_id: 2,
        type_id: 1,
        name: 'Law User',
        avatar:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
        role: {
          id: 2,
          name: 'Law Enforcement Personnel',
        },
      },
      incident_id: 4,
      status: 1,
      alert_type: 'alert',
      created_at: '2023-12-04T18:37:40.000000Z',
      updated_at: null,
    },
    {
      id: 2,
      details:
        'URGENT: Armed robbery reported at 123 Main Street. Please avoid the area. Stay indoors and remain vigilant. Police are on the scene. Updates to follow.',
      created_by: {
        id: 3,
        role_id: 2,
        type_id: 1,
        name: 'Law User',
        avatar:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
        role: {
          id: 2,
          name: 'Law Enforcement Personnel',
        },
      },
      incident_id: 4,
      status: 1,
      alert_type: 'threat',
      created_at: '2023-12-04T18:37:40.000000Z',
      updated_at: null,
    },
    {
      id: 3,
      details:
        'URGENT: Armed robbery reported at 123 Main Street. Please avoid the area. Stay indoors and remain vigilant. Police are on the scene. Updates to follow.',
      created_by: {
        id: 3,
        role_id: 2,
        type_id: 1,
        name: 'Law User',
        avatar:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
        role: {
          id: 2,
          name: 'Law Enforcement Personnel',
        },
      },
      incident_id: 4,
      status: 1,
      alert_type: 'alert',
      created_at: '2023-12-04T18:37:40.000000Z',
      updated_at: null,
    },
  ],
};

const OneEventData = {
  status: true,
  message: 'Incident Fetched Successfully!',
  errors: [],
  data: {
    id: 4,
    title: 'Armed Robbery In Progress',
    map_view:
      'https://www.google.co.in/maps/place/Parimal+Garden/@23.0208367,72.5086508,14z/data=!4m6!3m5!1s0x395e84fb558f676b:0x7c6636f0c8a9648e!8m2!3d23.0203135!4d72.5561606!16s%2Fg%2F1tkc526m?entry=ttu',
    address: 'Gita Mandir',
    city: 'Ahmedabad',
    state: 'Gujarat',
    suite: 'CG Road',
    zip_code: '380026',
    country: 'India',
    latitude: '23.0020033',
    longitude: '72.5597094',
    date: '2023-11-28',
    day: '',
    time: '12:45:00',
    crime_type_id: 17,
    severity_level_id: 2,
    created_by: 4,
    community_id: null,
    details: 'It is a crime',
    explicit_content: 0,
    is_verified: 0,
    status: 1,
    alert_created: 1,
    created_at: '2023-11-28T14:02:38.000000Z',
    updated_at: '2023-11-28T14:02:38.000000Z',
    total_comments_count: 8,
    incident_alert_count: 1,
    distance: 8.187942707298596,
    incident_alert: {
      id: 1,
      details: 'testtest',
      created_by: {
        id: 3,
        role_id: 2,
        type_id: 1,
        created_by: null,
        name: 'Law User',
        username: null,
        email: 'law@mailinator.com',
        email_verified_at: null,
        credibility_level: null,
        status: 1,
        avatar: 'http://codesamples.local/storage/user_avatar/user.jpg',
        created_at: '2023-11-17T11:54:09.000000Z',
        updated_at: null,
        role: {
          id: 2,
          name: 'Law Enforcement Personnel',
          slug: 'law-enforcement-personnel',
          status: 1,
          created_at: '2023-11-17T11:47:17.000000Z',
          updated_at: '2023-11-17T11:47:17.000000Z',
        },
      },
      incident_id: 4,
      status: 1,
      alert_type: 'alert',
      created_at: '2023-12-04T18:37:40.000000Z',
      updated_at: null,
    },
    crime_type: {
      id: 17,
      severity_level_id: 2,
      name: 'Komal Shukla',
      type: 'crime',
      status: 1,
      created_at: '2023-12-08T08:21:14.000000Z',
      updated_at: '2023-12-08T09:33:36.000000Z',
    },
    comments: [
      {
        id: 1,
        text: 'Main one',
        user_id: 4,
        incident_id: 4,
        comment_id: null,
        parent_id: null,
        created_at: '2023-12-06T06:34:22.000000Z',
        updated_at: '2023-12-06T06:34:22.000000Z',
        sub_comments: [
          {
            id: 2,
            text: 'Under 1',
            user_id: 4,
            incident_id: 4,
            comment_id: 1,
            parent_id: 1,
            created_at: '2023-12-06T06:34:49.000000Z',
            updated_at: '2023-12-06T06:34:49.000000Z',
            commented_by: {
              id: 4,
              role_id: 1,
              type_id: 5,
              created_by: null,
              name: 'Kassandra Hermiston',
              username: null,
              email: 'komalshukla@mailinator.com',
              email_verified_at: null,
              credibility_level: null,
              status: 0,
              avatar:
                'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
              created_at: '2023-11-27T08:01:30.000000Z',
              updated_at: '2023-12-12T14:35:16.000000Z',
            },
            parent_comment: {
              id: 1,
              text: 'Main one',
              user_id: 4,
              incident_id: 4,
              comment_id: null,
              parent_id: null,
              created_at: '2023-12-06T06:34:22.000000Z',
              updated_at: '2023-12-06T06:34:22.000000Z',
              commented_by: {
                id: 4,
                role_id: 1,
                type_id: 5,
                created_by: null,
                name: 'Kassandra Hermiston',
                username: null,
                email: 'komalshukla@mailinator.com',
                email_verified_at: null,
                credibility_level: null,
                status: 0,
                avatar:
                  'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
                created_at: '2023-11-27T08:01:30.000000Z',
                updated_at: '2023-12-12T14:35:16.000000Z',
              },
            },
          },
          {
            id: 5,
            text: 'Under 1',
            user_id: 4,
            incident_id: 4,
            comment_id: 2,
            parent_id: 1,
            created_at: '2023-12-06T06:45:01.000000Z',
            updated_at: '2023-12-06T06:45:01.000000Z',
            commented_by: {
              id: 4,
              role_id: 1,
              type_id: 5,
              created_by: null,
              name: 'Kassandra Hermiston',
              username: null,
              email: 'komalshukla@mailinator.com',
              email_verified_at: null,
              credibility_level: null,
              status: 0,
              avatar:
                'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
              created_at: '2023-11-27T08:01:30.000000Z',
              updated_at: '2023-12-12T14:35:16.000000Z',
            },
            parent_comment: {
              id: 2,
              text: 'Under 1',
              user_id: 4,
              incident_id: 4,
              comment_id: 1,
              parent_id: 1,
              created_at: '2023-12-06T06:34:49.000000Z',
              updated_at: '2023-12-06T06:34:49.000000Z',
              commented_by: {
                id: 4,
                role_id: 1,
                type_id: 5,
                created_by: null,
                name: 'Kassandra Hermiston',
                username: null,
                email: 'komalshukla@mailinator.com',
                email_verified_at: null,
                credibility_level: null,
                status: 0,
                avatar:
                  'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
                created_at: '2023-11-27T08:01:30.000000Z',
                updated_at: '2023-12-12T14:35:16.000000Z',
              },
            },
          },
          {
            id: 6,
            text: 'Under 1',
            user_id: 4,
            incident_id: 4,
            comment_id: 5,
            parent_id: 1,
            created_at: '2023-12-06T06:45:16.000000Z',
            updated_at: '2023-12-06T06:45:16.000000Z',
            commented_by: {
              id: 4,
              role_id: 1,
              type_id: 5,
              created_by: null,
              name: 'Kassandra Hermiston',
              username: null,
              email: 'komalshukla@mailinator.com',
              email_verified_at: null,
              credibility_level: null,
              status: 0,
              avatar:
                'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
              created_at: '2023-11-27T08:01:30.000000Z',
              updated_at: '2023-12-12T14:35:16.000000Z',
            },
            parent_comment: {
              id: 5,
              text: 'Under 1',
              user_id: 4,
              incident_id: 4,
              comment_id: 2,
              parent_id: 1,
              created_at: '2023-12-06T06:45:01.000000Z',
              updated_at: '2023-12-06T06:45:01.000000Z',
              commented_by: {
                id: 4,
                role_id: 1,
                type_id: 5,
                created_by: null,
                name: 'Kassandra Hermiston',
                username: null,
                email: 'komalshukla@mailinator.com',
                email_verified_at: null,
                credibility_level: null,
                status: 0,
                avatar:
                  'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
                created_at: '2023-11-27T08:01:30.000000Z',
                updated_at: '2023-12-12T14:35:16.000000Z',
              },
            },
          },
        ],
      },
      {
        id: 7,
        text: 'Main',
        user_id: 4,
        incident_id: 4,
        comment_id: null,
        parent_id: null,
        created_at: '2023-12-06T06:46:23.000000Z',
        updated_at: '2023-12-06T06:46:23.000000Z',
        sub_comments: [
          {
            id: 8,
            text: 'Under 2',
            user_id: 4,
            incident_id: 4,
            comment_id: 7,
            parent_id: 7,
            created_at: '2023-12-06T06:47:04.000000Z',
            updated_at: '2023-12-06T06:47:04.000000Z',
            commented_by: {
              id: 4,
              role_id: 1,
              type_id: 5,
              created_by: null,
              name: 'Kassandra Hermiston',
              username: null,
              email: 'komalshukla@mailinator.com',
              email_verified_at: null,
              credibility_level: null,
              status: 0,
              avatar:
                'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
              created_at: '2023-11-27T08:01:30.000000Z',
              updated_at: '2023-12-12T14:35:16.000000Z',
            },
            parent_comment: {
              id: 7,
              text: 'Main',
              user_id: 4,
              incident_id: 4,
              comment_id: null,
              parent_id: null,
              created_at: '2023-12-06T06:46:23.000000Z',
              updated_at: '2023-12-06T06:46:23.000000Z',
              commented_by: {
                id: 4,
                role_id: 1,
                type_id: 5,
                created_by: null,
                name: 'Kassandra Hermiston',
                username: null,
                email: 'komalshukla@mailinator.com',
                email_verified_at: null,
                credibility_level: null,
                status: 0,
                avatar:
                  'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
                created_at: '2023-11-27T08:01:30.000000Z',
                updated_at: '2023-12-12T14:35:16.000000Z',
              },
            },
          },
          {
            id: 9,
            text: 'Under 2',
            user_id: 4,
            incident_id: 4,
            comment_id: 8,
            parent_id: 7,
            created_at: '2023-12-06T06:47:42.000000Z',
            updated_at: '2023-12-06T06:47:42.000000Z',
            commented_by: {
              id: 4,
              role_id: 1,
              type_id: 5,
              created_by: null,
              name: 'Kassandra Hermiston',
              username: null,
              email: 'komalshukla@mailinator.com',
              email_verified_at: null,
              credibility_level: null,
              status: 0,
              avatar:
                'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
              created_at: '2023-11-27T08:01:30.000000Z',
              updated_at: '2023-12-12T14:35:16.000000Z',
            },
            parent_comment: {
              id: 8,
              text: 'Under 2',
              user_id: 4,
              incident_id: 4,
              comment_id: 7,
              parent_id: 7,
              created_at: '2023-12-06T06:47:04.000000Z',
              updated_at: '2023-12-06T06:47:04.000000Z',
              commented_by: {
                id: 4,
                role_id: 1,
                type_id: 5,
                created_by: null,
                name: 'Kassandra Hermiston',
                username: null,
                email: 'komalshukla@mailinator.com',
                email_verified_at: null,
                credibility_level: null,
                status: 0,
                avatar:
                  'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
                created_at: '2023-11-27T08:01:30.000000Z',
                updated_at: '2023-12-12T14:35:16.000000Z',
              },
            },
          },
          {
            id: 10,
            text: 'Under 2',
            user_id: 4,
            incident_id: 4,
            comment_id: 8,
            parent_id: 7,
            created_at: '2023-12-06T11:13:45.000000Z',
            updated_at: '2023-12-06T11:13:45.000000Z',
            commented_by: {
              id: 4,
              role_id: 1,
              type_id: 5,
              created_by: null,
              name: 'Kassandra Hermiston',
              username: null,
              email: 'komalshukla@mailinator.com',
              email_verified_at: null,
              credibility_level: null,
              status: 0,
              avatar:
                'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
              created_at: '2023-11-27T08:01:30.000000Z',
              updated_at: '2023-12-12T14:35:16.000000Z',
            },
            parent_comment: {
              id: 8,
              text: 'Under 2',
              user_id: 4,
              incident_id: 4,
              comment_id: 7,
              parent_id: 7,
              created_at: '2023-12-06T06:47:04.000000Z',
              updated_at: '2023-12-06T06:47:04.000000Z',
              commented_by: {
                id: 4,
                role_id: 1,
                type_id: 5,
                created_by: null,
                name: 'Kassandra Hermiston',
                username: null,
                email: 'komalshukla@mailinator.com',
                email_verified_at: null,
                credibility_level: null,
                status: 0,
                avatar:
                  'http://codesamples.local/storage/user_avatar/656865f6ea1ba.jpg',
                created_at: '2023-11-27T08:01:30.000000Z',
                updated_at: '2023-12-12T14:35:16.000000Z',
              },
            },
          },
        ],
      },
    ],
    media: [
      {
        id: 6,
        name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
        uploaded_name: 'Cats.jpg',
        type: 'image/jpeg',
        incident_id: 4,
        created_at: '2023-11-28T14:02:38.000000Z',
        updated_at: '2023-11-28T14:02:38.000000Z',
      },
      {
        id: 7,
        name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
        uploaded_name: 'Eyes.jpg',
        type: 'image/jpeg',
        incident_id: 4,
        created_at: '2023-11-28T14:02:38.000000Z',
        updated_at: '2023-11-28T14:02:38.000000Z',
      },
      {
        id: 8,
        name: 'https://static.toiimg.com/thumb/msid-105983668,imgsize-33700,width-400,resizemode-4/105983668.jpg',
        uploaded_name: 'Orange.jpg',
        type: 'image/jpeg',
        incident_id: 4,
        created_at: '2023-11-28T14:02:38.000000Z',
        updated_at: '2023-11-28T14:02:38.000000Z',
      },
    ],
    severity_level: {
      id: 2,
      name: 'Moderate',
      range: '4 to 6',
      color_code: 'Orange',
      status: 1,
      created_at: '2023-11-17T11:47:17.000000Z',
      updated_at: '2023-11-17T11:47:17.000000Z',
    },
  },
};

// export const CommentsLevelOne = {
//   totalComments: 100,
//   comments: [
//     {
//       id: 1,
//       text: 'Great post!',
//       posted_by: 'user1',
//       parentId: null,
//       timestamp: 'Feb 23, 1:23 AM',
//       totalReplies: 5,
//     },
//     {
//       id: 2,
//       text: 'Thanks!',
//       posted_by: 'user2',
//       parentId: null,
//       timestamp: 'Feb 23, 1:23 AM',
//       totalReplies: 3,
//     },
//     {
//       id: 2,
//       text: 'Thanks!',
//       posted_by: 'user2',
//       parentId: null,
//       timestamp: 'Feb 23, 1:23 AM',
//       totalReplies: 3,
//     },
//     {
//       id: 2,
//       text: 'Thanks!',
//       posted_by: 'user2',
//       parentId: null,
//       timestamp: 'Feb 23, 1:23 AM',
//       totalReplies: 3,
//     },
//     {
//       id: 2,
//       text: 'Thanks!',
//       posted_by: 'user2',
//       parentId: null,
//       timestamp: 'Feb 23, 1:23 AM',
//       totalReplies: 3,
//     },
//   ],
//   pagination: {
//     currentPage: 1,
//     totalPages: 5,
//     pageSize: 10,
//   },
// };

// export const CommentsLevelTwo = {
//   totalReplies: 10,
//   replies: [
//     {
//       id: 1,
//       text: 'Thanks!',
//       posted_by: 'user3',
//       parentId: 1,
//       timestamp: 'Feb 23, 1:23 AM',
//     },
//     {
//       id: 2,
//       text: "You're welcome!",
//       posted_by: 'user1',
//       parentId: 1,
//       timestamp: 'Feb 23, 1:23 AM',
//     },
//   ],
//   pagination: {
//     currentPage: 1,
//     totalPages: 3,
//     pageSize: 5,
//   },
// };

export const CommentsLevelOne = {
  totalComments: 100,
  comments: [
    {
      id: 101,
      text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
      posted_by: 'Manthan patel',
      parentId: null,
      timestamp: 'Feb 23, 1:23 AM',
      totalReplies: 5,
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
    {
      id: 102,
      text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
      posted_by: 'Tushar karamchandani karamchandani',
      parentId: null,
      timestamp: 'Feb 23, 1:23 AM',
      totalReplies: 3,
      user_Img:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOmoml8O8mN99-mk1QV3nKiGaNvPLvl27hpw&usqp=CAU',
    },
    // {
    //   id: 103,
    //   text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
    //   posted_by: 'Tushar karamchandani karamchandani',
    //   parentId: null,
    //   timestamp: 'Feb 23, 1:23 AM',
    //   totalReplies: 3,
    //   user_Img:
    //     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOmoml8O8mN99-mk1QV3nKiGaNvPLvl27hpw&usqp=CAU',
    // },
    // {
    //   id: 104,
    //   text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
    //   posted_by: 'Tushar karamchandani karamchandani',
    //   parentId: null,
    //   timestamp: 'Feb 23, 1:23 AM',
    //   totalReplies: 3,
    //   user_Img:
    //     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOmoml8O8mN99-mk1QV3nKiGaNvPLvl27hpw&usqp=CAU',
    // },
    // {
    //   id: 105,
    //   text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
    //   posted_by: 'Tushar karamchandani karamchandani',
    //   parentId: null,
    //   timestamp: 'Feb 23, 1:23 AM',
    //   totalReplies: 3,
    //   user_Img:
    //     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOmoml8O8mN99-mk1QV3nKiGaNvPLvl27hpw&usqp=CAU',
    // },
  ],
  pagination: {
    currentPage: 1,
    totalPages: 5,
    pageSize: 10,
  },
};

export const CommentsLevelTwo = {
  totalReplies: 10,
  replies: [
    {
      id: 201,
      text: 'Thanks!',
      posted_by: 'Manthan patel',
      parentId: 101,
      timestamp: 'Feb 23, 1:23 AM',
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
    {
      id: 202,
      text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
      posted_by: 'Tiger Smith',
      parentId: 101,
      timestamp: 'Feb 23, 1:23 AM',
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
  ],
  pagination: {
    currentPage: 1,
    totalPages: 3,
    pageSize: 5,
  },
};

export const CommentsLevelTwoData2 = {
  totalReplies: 10,
  replies: [
    {
      id: 203,
      text: 'Thanks!',
      posted_by: 'zuber morkas',
      parentId: 102,
      timestamp: 'Feb 23, 1:23 AM',
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
    {
      id: 204,
      text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
      posted_by: 'arbaz pathan',
      parentId: 102,
      timestamp: 'Feb 23, 1:23 AM',
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
  ],
  pagination: {
    currentPage: 1,
    totalPages: 3,
    pageSize: 5,
  },
};

export const CommentsLevelTwoData2_2 = {
  totalReplies: 10,
  replies: [
    {
      id: 205,
      text: 'Thanks!',
      posted_by: 'sean smit',
      parentId: 102,
      timestamp: 'Feb 23, 1:23 AM',
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
    {
      id: 206,
      text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
      posted_by: 'setupati pathan',
      parentId: 102,
      timestamp: 'Feb 23, 1:23 AM',
      user_Img:
        'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
    },
  ],
  pagination: {
    currentPage: 2,
    totalPages: 3,
    pageSize: 5,
  },
};

export const CombinedComments = {
  comment: {
    id: 101,
    text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
    posted_by: 'Manthan patel',
    parentId: null,
    timestamp: 'Feb 23, 1:23 AM',
    totalReplies: 5,
    user_Img:
      'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
  },
  replies: {
    totalReplies: 10,
    data: [
      {
        id: 201,
        text: 'Thanks!',
        posted_by: 'Manthan patel',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      {
        id: 202,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },

      {
        id: 203,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      {
        id: 204,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      {
        id: 205,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      // ... (more replies based on pagination)
    ],
    pagination: {
      currentPage: 1,
      totalPages: 2,
      pageSize: 5,
    },
  },
};

export const CombinedCommentsPage2 = {
  comment: {
    id: 101,
    text: 'Witnessing an armed robbery at 123 Main Street. Multiple perpetrators, three individuals armed with firearms, are actively involved. Eyewitnes',
    posted_by: 'Manthan patel',
    parentId: null,
    timestamp: 'Feb 23, 1:23 AM',
    totalReplies: 5,
    user_Img:
      'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
  },
  replies: {
    totalReplies: 10,
    data: [
      {
        id: 222,
        text: 'Thanks!',
        posted_by: 'Manthan patel',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      {
        id: 223,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },

      {
        id: 223,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      {
        id: 224,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      {
        id: 225,
        text: 'i saw it too and it was happening infont of the policeman but he was busy talking about on call so i dont know what whts to say.',
        posted_by: 'Tiger Smith',
        parentId: 101,
        timestamp: 'Feb 23, 1:23 AM',
        user_Img:
          'https://ui.tradeshift.com/v10/dist/components/userimages/assets/jim.png',
      },
      // ... (more replies based on pagination)
    ],
    pagination: {
      currentPage: 2,
      totalPages: 2,
      pageSize: 5,
    },
  },
};
